### ISSUE TITLE
Formatting and Commenting

### ISSUE THREAD

**Issue by cyouh95** [jcochran206/DasmotoArt#1]
Great job on the formatting and indenting of your code! But one thing to note about commenting is that in CSS, the syntax for comments is:

```css
/* This is a comment. */
``` 

(like what you have [here](https://github.com/jcochran206/DasmotoArt/blob/master/DasmotoArts/resources/css/style.css#L4))

Double slash (`//`) is not valid syntax and will actually "comment out" the entire first `.header h1` [block](https://github.com/jcochran206/DasmotoArt/blob/master/DasmotoArts/resources/css/style.css#L3-L11).

https://github.com/jcochran206/DasmotoArt/blob/5081f61122a334e45b97bc379c2526b10ee63967/DasmotoArts/resources/css/style.css#L1

Here is a good resource on this: https://www.xanthir.com/b4U10

**Comment by jcochran206** [comment]
created comments for section
