### ISSUE TITLE
CSS inheritance

### ISSUE THREAD

**Issue by cyouh95** [jcochran206/DasmotoArt#3]
In many cases, children elements inherit CSS properties from their parent elements. You could take advantage of that to help you avoid repetition in code. For example, you are currently specifying `font-family: Helvetica;` in all of your CSS rules [here](https://github.com/jcochran206/DasmotoArt/blob/master/DasmotoArts/resources/css/style.css). Instead, if you want to specify this font for all of your elements, you could use `body` as your selector. That way, since all elements are children of the `body` element, they will automatically inherit this property.

```css
body {
  font-family: Helvetica;
}
```

**Comment by jcochran206** [comment]
updated css to reflect inheritance of font-family
