### ISSUE TITLE
Class for styling elements

### ISSUE THREAD

**Issue by cyouh95** [jcochran206/DasmotoArt#4]
Alternatively, you could apply a class to your `span` elements and use that as the selector [here](https://github.com/jcochran206/DasmotoArt/blob/master/DasmotoArts/resources/css/style.css#L36) to style the text. That way, in case you want to use the `span` element for something else later, they won't all already be styled blue, for example.

HTML:
```html
<span class="price">Starting at $3.00 / brush.</span>
...
<span class="price">Starting at $2.00 / frame.</span>
...
<span class="price">Starting at $5.00 / tube.</span>
```

CSS:
```css
.price {
  ...
}
```

https://github.com/jcochran206/DasmotoArt/blob/master/DasmotoArts/index.html#L16
https://github.com/jcochran206/DasmotoArt/blob/master/DasmotoArts/index.html#L22
https://github.com/jcochran206/DasmotoArt/blob/master/DasmotoArts/index.html#L28

**Comment by jcochran206** [comment]
updated span to have price class and updated css to reflect changes
