### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by cyouh95** [jcochran206/DasmotoArt#5]
(Meets Expectations)

Nice job with this project! It looks like you have a good understanding of how HTML and CSS work together for display of content. You were able to recreate all the main components of this webpage so well done!

One thing you could continue to explore are ways to simplify your code and reduce repetition (#2, #3). Here is a also a good resource on using `class`es and `id`s for styling your elements: http://www.turnwall.com/articles/basic-styling-with-css-class-id/

And as a further challenge, try creating your own page from scratch without the use of any specs or template. You definitely already have a good sense of how to organize and structure your code - this will be great practice for continuing to build your skills! Happy coding!

**Comment by jcochran206** [comment]
Thank you I will continue and check this link out
